languageCode = "en"
languageName = "English"
weight = 1
title = "Atops Dungeon"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "Hello, What are you looking for?"
logo = "./assets/Sir-Atops.png"

[author]
name = "Atops"
links = [ { github = "https://github.com/Atops93" }, { youtube = "https://youtube.com/channel/UCLS0O5xNxh2c4mx5xy5g25g" } ]
image = "Sir-Atops.jpg"
headline = "I'm just Atops"
bio = "Goofy ah Atops"